export const InputFields = [
  {
    label: "Tittle",
    placeholder:
      '"Enter where you spend or receive money (e.g., salary, shopping)"',
    type: "text",
    name: "Tittle",
    required: true,
    value: form.name,
  },
  {
    label: "Amount",
    placeholder: "enter your amount",
    type: "number",
    name: "amount",
    required: true,
    min: 0,
    value: form.name,
  },
  {
    label: "Date of Transaction",

    type: "date",
    name: "TransactionDate",
    required: true,
    value: form.name,
  },
  {
    label: "First Name",
    placeholder: "enter your first name",
    type: "text",
    name: "Fname",
    required: true,
    value: form.name,
  },
  {
    label: "Last Name",
    placeholder: "enter your Last name",
    type: "text",
    name: "Lname",
    required: true,
    value: form.name,
  },
  {
    label: "Email",
    placeholder: "enter your email",
    type: "email",
    name: "email",
    required: true,
    value: form.name,
  },
  {
    label: "Password",
    placeholder: "enter your password",
    type: "password",
    name: "passwordHashed",
    required: true,
    autoComplete: "new-password",
    value: form.name,
  },
  {
    label: "Confirm Password",
    placeholder: "enter confirmed password",
    type: "password",
    name: "confirmPasswordHashed",
    autoComplete: "new-password",
    required: true,
    value: form.name,
  },

  {
    label: " New Password",
    placeholder: " enter new password",
    type: "password",
    name: "NewPasswordHashed",
    autoComplete: "new-password",
    required: true,
    value: form.name,
  },
  {
    label: "Confirm New Password",
    placeholder: " confirmed new password",
    type: "password",
    name: "confirmNewPasswordHashed",
    autoComplete: "new-password",
    required: true,
    value: form.name,
  },
];
